### ISSUE TITLE
Select Color Scheme

### ISSUE THREAD

**Issue by jovanyoshioka** [jovanyoshioka/CityFinder#1]
**Task**
1.) Select a color scheme for the web app. Define what colors to use for text, backgrounds, and buttons. Provide the Hex color code (e.g., "#FF0000") or RGB value (e.g., "(255, 0, 0)").
2.) Add CSS variables for the color codes under `:root` in `css/global.css` file. Reference `Example A`. Feel free to change the variable names as you see fit.

**Resources**
Online Color Scheme Generator: https://coolors.co/generate

**Example A**
![select_color_scheme_example_a](https://github.com/jovanyoshioka/CityFinder/assets/54458982/49a31d98-29f8-4386-8431-7d056c837226)

**Comment by KoobDS** [comment]
Maybe I am not built different in the color department, after all

**Comment by arwen09** [comment]
<img width="1215" alt="Screenshot 2024-04-19 at 1 56 39 PM" src="https://github.com/jovanyoshioka/CityFinder/assets/161878730/4a22f21f-418e-4c8d-8dd6-3f21be81d00c">
