### ISSUE TITLE
[Preferences] Add Slider

### ISSUE THREAD

**Issue by jovanyoshioka** [jovanyoshioka/CityFinder#15]
**Task**
In addition to the rating radio buttons, add a slider for goldilock features.

**Comment by KoobDS** [comment]
{'VALUEH_median': [175000, 9999999, USD], 'AGE_mean': [31, 60, years], 'Annual_Precip': [0, 99, inches], 'Annual_Snowfall': [0, 220, inches], 'Winter_Temp': [4, 72, Fahrenheit], 'Summer_Temp': [56, 88, Fahrenheit]}
